// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.WindowManager.UpdateDtrEntry")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.NNekoTriggers.ShouldDoENF~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.WindowManager.InitializeDtrEntries")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.Windows.SettingsWindow.#ctor")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.NNekoTriggers.ClientState_ClassJobChanged(System.UInt32)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.NNekoTriggers.ClientState_MapIdChanged(System.UInt32)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.NNekoTriggers.ClientState_ZoneInit(Dalamud.Game.ClientState.ZoneInitEventArgs)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.NNekoTriggers.OnTerritoryChanged(System.UInt16)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.NNekoTriggers.ClientState_OnLogin")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.NNekoTriggers.HandleZoneTriggerENF(NNekoTriggers.Configuration.CharacterConfiguration,NNekoTriggers.Configuration.CustomCommand)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.WindowManager.ToggleConfigWindow")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.Windows.SettingsWindow.DrawConditions~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.WindowManager.#ctor(Dalamud.Plugin.Services.IFramework,Dalamud.Plugin.Services.IDtrBar)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.WindowManager.Dispose")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.Windows.SettingsWindow.Draw")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.WindowManager.OnLogin")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.WindowManager.OnLogout(System.Int32,System.Int32)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.WindowManager.OnFrameworkUpdate(Dalamud.Plugin.Services.IFramework)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~P:NNekoTriggers.UI.WindowManager.RpOnlyEntry")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~P:NNekoTriggers.UI.WindowManager.RngEntry")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~P:NNekoTriggers.UI.WindowManager.ZoneEntry")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~P:NNekoTriggers.UI.WindowManager.GearsetEntry")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~P:NNekoTriggers.UI.WindowManager.OverrideEntry")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~P:NNekoTriggers.UI.WindowManager.OnLoginEntry")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.NNekoTriggers.Dispose")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.NNekoTriggers.#ctor")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~P:NNekoTriggers.NNekoTriggers.Toast")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~F:NNekoTriggers.NNekoTriggers.ToastOptions")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.Command.CommandManager.#ctor")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.Command.CommandManager.OnCommand(System.String,System.String)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.Helpers.Utils.GetCharacterConfig~NNekoTriggers.Configuration.CharacterConfiguration")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~F:NNekoTriggers.Helpers.Utils.BusyFlags")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.Command.CommandManager.Dispose")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.Helpers.Utils.IsBetweenAreas~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.Configuration.PluginConfiguration.Load~NNekoTriggers.Configuration.PluginConfiguration")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.Configuration.PluginConfiguration.Save")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.Helpers.Utils.IsCastingTeleportAction(System.UInt32)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.NNekoTriggers.OnTerritoryChanged(System.UInt32)")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:NNekoTriggers.UI.WindowManager.#ctor(Dalamud.Plugin.Services.IFramework)")]
